LOCAL_CPPFLAGS := -DSDKBOX_ENABLED \
-DSDKBOX_COCOS_CREATOR
LOCAL_WHOLE_STATIC_LIBRARIES := PluginReview \
sdkbox \
PluginSdkboxAds \
PluginAdMob \
PluginUnityAds
LOCAL_WHOLE_STATIC_LIBRARIES := 
$(call import-add-path,$(LOCAL_PATH))
$(call import-module, ./sdkbox)
$(call import-module, ./PluginReview)
$(call import-module, ./PluginSdkboxAds)
$(call import-module, ./PluginAdMob)
$(call import-module, ./PluginUnityAds)
LOCAL_LDLIBS := -landroid \
-llog
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
LOCAL_WHOLE_STATIC_LIBRARIES := 
